package com.retailpos.security;

import java.time.LocalDateTime;
import java.util.List;
import java.util.Optional;

import com.retailpos.model.Session;
import com.retailpos.repository.SessionRepository;

public class SessionService {

    private final SessionRepository sessionRepository;

    public SessionService(SessionRepository sessionRepository) {
        this.sessionRepository = sessionRepository;
    }

    public Session createSession(
            String userId,
            String username,
            String deviceId
    ) {

        LocalDateTime now = LocalDateTime.now();

        Session session = new Session(
                userId,
                username,
                deviceId,
                now,
                now,
                "ACTIVE"
        );

        /*
         * Session ID will be generated by MongoDB.
         */
        sessionRepository.save(session);

        return session;
    }

    public Optional<Session> findById(String sessionId) {

        return sessionRepository.findById(sessionId);
    }

    public List<Session> getActiveSessions() {

        return sessionRepository.findActiveSessions();
    }

    public List<Session> getUserSessions(String username) {

        return sessionRepository.findByUsername(username);
    }

    public void updateActivity(Session session) {

        if (session == null) {
            return;
        }

        if (!"ACTIVE".equals(session.getStatus())) {
            return;
        }

        session.setLastActivityAt(
                LocalDateTime.now()
        );

        sessionRepository.update(session);
    }

    public void logout(Session session) {

        if (session == null) {
            return;
        }

        if (!"ACTIVE".equals(session.getStatus())) {
            return;
        }

        session.setStatus("LOGGED_OUT");

        session.setLogoutAt(
                LocalDateTime.now()
        );

        sessionRepository.update(session);
    }

    public boolean forceLogout(String sessionId) {

        Optional<Session> optionalSession =
                sessionRepository.findById(sessionId);

        if (optionalSession.isEmpty()) {
            return false;
        }

        Session session = optionalSession.get();

        if (!"ACTIVE".equals(session.getStatus())) {
            return false;
        }

        session.setStatus("FORCE_LOGGED_OUT");

        session.setLogoutAt(
                LocalDateTime.now()
        );

        sessionRepository.update(session);

        return true;
    }
}